import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { modalSliceAction } from "@/feature/modal/modalSlice";
import HowToPlayModal from "@/components/common/modal/HowToPlayModal";
import styled from "styled-components";
// import styled from "";

const Main = styled.main`
  text-align: center;
  padding-top: 300px;
  min-height: 100vh;
  background-color: antiquewhite;
`;

const PlayButton = styled.button`
  padding: 10px;
  font-size: 25px;
  margin: auto;
  cursor: pointer;
  font-weight: bold;
  border-radius: 15px;
  background-color: gray;
  color: white;
  border-color: aliceblue;
  margin-top: 10px;
`;

export default function Home() {
  const [choice, setChoice] = useState("");
  const router = useRouter();
  const dispatch = useDispatch();
  const gameStart = () => {
    if (!choice) return;
    router.push(`/game?level=${parseInt(choice)}`);
  };
  const selectLevel = (e: any) => {
    setChoice(e.target.value);
  };

  const openModal = () => {
    console.log("???");
    dispatch(modalSliceAction.setIsOpenHowToPlayModal(true));
  };
  return (
    <>
      <Head>
        <title>미니 게임</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Main>
        <div>
          테스트
          <select onChange={(e) => selectLevel(e)}>
            <option value="">{"단계"}</option>
            <option value="8">{"1"}</option>
            <option value="12">{"2"}</option>
            <option value="20">{"3"}</option>
          </select>
        </div>

        <div>
          <PlayButton onClick={gameStart}>
            {/* <button
            className={choice ? styles.playBtn : styles.forbiddenBtn}
            onClick={gameStart}
            disabled={choice ? false : true}
          > */}
            {"PLAY THE GAME"}
          </PlayButton>
        </div>
        <div>
          <button className={styles.playBtn} onClick={openModal}>
            {"HOW TO PLAY"}
          </button>
        </div>
      </Main>
      <HowToPlayModal />
    </>
  );
}
