import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [choice, setChoice] = useState("");
  const router = useRouter();
  const gameStart = () => {
    console.log(choice);
    if (!choice) return;
    router.push(`/game?level=${parseInt(choice)}`);
  };
  const selectLevel = (e: any) => {
    console.log(e.target.value);
    setChoice(e.target.value);
  };
  return (
    <>
      <Head>
        <title>미니 게임</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <div>
          <select onChange={(e) => selectLevel(e)}>
            <option value="">{"단계"}</option>
            <option value="8">{"1"}</option>
            <option value="12">{"2"}</option>
            <option value="20">{"3"}</option>
          </select>
        </div>

        <div>
          <button
            className={choice ? styles.playBtn : styles.forbiddenBtn}
            onClick={gameStart}
            disabled={choice ? false : true}
          >
            {"PLAY THE GAME"}
          </button>
        </div>
        <div>
          <button className={styles.playBtn} onClick={gameStart}>
            {"HOW TO PLAY"}
          </button>
        </div>
      </main>
    </>
  );
}
